version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ML_SERVICE_URL=http://ml:8000
      - STORAGE_DIR=/data
    volumes:
      - data:/data
    depends_on:
      - ml

  ml:
    build: ./ml_service
    ports:
      - "8000:8000"
    volumes:
      - data:/data

volumes:
  data:
